### ISSUE TITLE
Does not patch League Client?

### ISSUE THREAD

**Issue by howardwch** [Crauzer/Flow#1]
This has been working flawlessly for me when I modify my skin files, but would it work if I modify wad assets using obsidian on the league_client instead of the lol_game_client skin assets? I want to customize the client images or maybe even tweak some values. After patching leagueclient.exe on League of Legends folder, loading screen remains stuck after logging in. Im not sure if this part matters but I also tried patching LeagueClientUX and LeagueClient.exe on projects/league_client/releases/installer/deploy/ and it gave me an error.

**Comment by Crauzer** [comment]
I am pretty sure the only thing you need to edit is either LeagueClient.exe in the main League folder or LeagueClient.exe in the latest release of the client
